version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ecom-rabbit-ts-network

  auth-db:
    container_name: auth-db
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - auth-data:/data/db
    networks:
      - ecom-rabbit-ts-network

  authentication:
    container_name: authentication
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://auth-db:27017/ecom-rabbit-ts
      - MESSAGE_BUS=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecom-rabbit-ts-network

  user-db:
    container_name: user-db
    image: mongo
    ports:
      - "27021:27017"
    volumes:
      - user-data:/data/db
    networks:
      - ecom-rabbit-ts-network

  user-management:
    container_name: user-management
    build:
      context: ./services/user-management
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://user-db:27017/ecom-rabbit-ts
      - MESSAGE_BUS=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecom-rabbit-ts-network

  product-db:
    container_name: product-db
    image: mongo
    ports:
      - "27022:27017"
    volumes:
      - product-data:/data/db
    networks:
      - ecom-rabbit-ts-network

  product-management:
    container_name: product-management
    build:
      context: ./services/product-management
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://product-db:27017/ecom-rabbit-ts
      - MESSAGE_BUS=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecom-rabbit-ts-network

  cart-db:
    container_name: cart-db
    image: mongo
    ports:
      - "27023:27017"
    volumes:
      - cart-data:/data/db
    networks:
      - ecom-rabbit-ts-network

  cart-management:
    container_name: cart-management
    build:
      context: ./services/cart-management
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://cart-db:27017/ecom-rabbit-ts
      - MESSAGE_BUS=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecom-rabbit-ts-network      

  order-db:
    container_name: order-db
    image: mongo
    ports:
      - "27024:27017"
    volumes:
      - order-data:/data/db
    networks:
      - ecom-rabbit-ts-network

  order-management:
    container_name: order-management
    build:
      context: ./services/order-management
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://order-db:27017/ecom-rabbit-ts
      - MESSAGE_BUS=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecom-rabbit-ts-network  


volumes:
  auth-data:
  user-data:
  product-data:
  cart-data:
  order-data:


networks:
  ecom-rabbit-ts-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"